baseURL = "https://restaurant-guide.github.io/"
theme = "hugo-PaperMod"
languageCode = "en-us"
title = "Restaurant Guide for North America"

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = true
buildFuture = false
buildExpired = false
enableEmoji = true

[params]
  env = "production"
  author = ["Ellen Winther Mortensen", "Julius  Pulvertaft Rasmussen", "Michelle Siw Hovendal"]
  defaultTheme = "auto"
  ShowShareButtons = false
  ShowReadingTime = false
  displayFullLangName = true
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowToc = false

  [params.homeInfoParams]
  Title = "About this webpage"
  Content = """
  This webpage is made by Ellen Winther Mortensen, Julius Pulvertaft Rasmussen, and Michelle Siw Hovendal 
and is part of the final project in the course Social Data Analysis and Visualization at Technical
University of Denmark (DTU). This webpage is made in spring 2021.

The aim of the webpage is about restaurants placed in North America, the data is based on [yelp data](https://www.yelp.com/dataset). 
The Python explainer notebook is attached [here](https://github.com/Restaurant-Guide/Restaurant-Guide/blob/master/code/Explainer%20Notebook.ipynb). 	
"""

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/Restaurant-Guide/Restaurant-Guide/wiki"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://youtu.be/tP36rm07aRA"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1


[markup.goldmark.renderer]
    unsafe = true

