baseURL = "https://restaurant-guide.github.io/"
theme = "hugo-PaperMod"
languageCode = "en-us"
title = "Restaurant Guide for North America"

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = true
buildFuture = false
buildExpired = false
enableEmoji = true

[params]
  env = "production"
  author = ["Ellen Winther Mortensen, Julius  Pulvertaft Rasmussen and Michelle Hovendal"]
  defaultTheme = "auto"
  ShowShareButtons = false
  ShowReadingTime = false
  displayFullLangName = true
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowToc = false

  [params.homeInfoParams]
  Title = "About this webpage"
  Content = """
This webpage is made by Ellen Winther Mortensen, Julius Pulvertaft Rasmussen and Michelle Siw Hovendal. 
This is a part of the final project in the course Social Data Analysis and Visualization at Technical 
University of Denmark (DTU). This webpage is made in spring 2021.

The aim of the webpage is to help the user find their new restaurant visit without thinking about fake reviews. 
Thus, developing a machine learning model that detects fake reviews and removes them from our dataset.

If you are interested, check out our Python Explainer notebook[here](https://github.com/Restaurant-Guide/Restaurant-Guide/blob/master/code/Explainer%20Notebook.ipynb).
But feel free to check out our GitHub repo by clicking the GitHub logo below.  	
"""

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/Restaurant-Guide/Restaurant-Guide/wiki"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://youtu.be/tP36rm07aRA"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1


[markup.goldmark.renderer]
    unsafe = true

