baseURL = "https://restaurant-guide.github.io/"
theme = "hugo-PaperMod"
languageCode = "en-us"
title = "Restaurant Guide for North America"

[[menu.main]]
    name = "Front page"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "post/about"
    weight = 2
